version: 2.1
orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.6
jobs:
  build-and-deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '14.18.0'
      - run: node --version
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - run:
          name: hello
          command: |
            echo "Hello! Starting the deployment process!"
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:   
          filters:
            branches:
              only: master